### ISSUE TITLE
Move API from Parmyay into its own repo.

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyaymobile#3]
Since the Parmyay and Parmyaymobile will both be presumably using the same API, I think it is appropriate to have it moved into its own repo.

**Comment by JonathanHolland** [comment]
Yes! We definitely need to do this with the new addition of a mobile
platform

**Comment by MrCeleryman** [comment]
Should we move the web to its own repo and leave the api in Parmyay and make Parmyayweb?

**Comment by CaptainAchilles** [comment]
I think moving the web to its own repo is a better option.

**Comment by MrCeleryman** [comment]
Ok I will make an issue on the Parmyay Repo to move the Web to a new Repo called Parmyayweb and also create that repo in the process 💃
